# Frequency for model saving
DEADLOCK_ITERATION_SAVE_INTERVAL = 5
EXPLORATION_ITERATION_SAVE_INTERVAL = 5
FULL_COST_ITERATION_SAVE_INTERVAL = -1

PRINTING_INTERVAL = 5

# Training iterations and timesteps per iteration
MAX_DEADLOCK_ITERATIONS = 10
DEADLOCK_TIMESTEPS = 5000
MAX_EXPLORATION_ITERATIONS = 20
EXPLORATION_TIMESTEPS = 5000
MAX_FULL_COST_ITERATIONS = 50
FULL_COST_TIMESTEPS = 10000
MAX_TESTING_TIMESTEPS = 1000

# Reward definitions
DEADLOCK_OCCURS_REWARD = -100000.0
INVALID_STATE_REWARD = -100000.0
GOAL_FOUND_REWARD = 10000.0
STEP_REWARD = -0.1
FIRST_TIME_ACTION_REWARD = 100.0

# Default input file (petri net)
FILENAME = "job.json"

# Directories
models_dir = f"models/PetriNet-PPO/"
logdir = f"logs/"

# 
ONE_TIME_KEY = "once"
EXTRAPOLATED_KEY = "extrapolated"
ONE_TIME_INDEX = 0
EXTRAPOLATED_INDEX = 1

ERGO_KEY = "ergonomic"
MONETARY_KEY = "monetary"