DEADLOCK_TRAINING = True
DEADLOCK_ITERATION_SAVE_INTERVAL = 1
PPO_ITERATION_SAVE_INTERVAL = 1
MAX_DEADLOCK_ITERATIONS = 25
DEADLOCK_TIMESTEPS = 10000
MAX_PPO_ITERATIONS = 100
PPO_TIMESTEPS = 10000
FILENAME = "cost_net.json"